"""Render docs/features/README.md from the per-feature markdown files.

Reads the YAML frontmatter at the top of every `*.md` under
`docs/features/` (excluding `README.md`), groups them by `section:`, and
emits a deterministic markdown index. Used by
`scripts/render-features-index.sh`.

Design notes:
- No external YAML dep: we parse a tiny, well-known frontmatter subset
  (scalars and one-level lists). The agent-farm pyproject already
  declares pyyaml as a dep, but keeping this script stdlib-only means
  the CI gate doesn't need a poetry install just to verify drift.
- Stable ordering: sections sorted by their leading numeric prefix when
  present, then by name. Within a section, features sorted by name.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import Any


_FRONTMATTER_RX = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def parse_frontmatter(text: str) -> dict[str, Any]:
    """Parse YAML frontmatter with scalar + one-level list values."""
    match = _FRONTMATTER_RX.match(text)
    if not match:
        return {}
    body = match.group(1)
    out: dict[str, Any] = {}
    current_list_key: str | None = None
    for raw_line in body.splitlines():
        line = raw_line.rstrip()
        if not line:
            current_list_key = None
            continue
        if line.startswith("  - ") and current_list_key is not None:
            out.setdefault(current_list_key, []).append(line[4:].strip())
            continue
        if ":" not in line:
            current_list_key = None
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if not value:
            current_list_key = key
            out.setdefault(key, [])
            continue
        current_list_key = None
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        out[key] = value
    return out


def section_sort_key(section: str) -> tuple[int, str]:
    leading = re.match(r"(\d+)", section)
    if leading is None:
        return (10_000, section)
    return (int(leading.group(1)), section)


def load_features(features_dir: pathlib.Path) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for path in sorted(features_dir.glob("*.md")):
        if path.name == "README.md":
            continue
        text = path.read_text(encoding="utf-8")
        meta = parse_frontmatter(text)
        if not meta:
            continue
        meta["_path"] = path.name
        out.append(meta)
    return out


def render(features: list[dict[str, Any]]) -> str:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for feat in features:
        section = str(feat.get("section", "99-misc"))
        grouped.setdefault(section, []).append(feat)

    lines: list[str] = []
    lines.append("# Features inventory")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/render-features-index.sh` from the per-feature"
    )
    lines.append(
        "markdown pages in this directory. Do not edit by hand; edit the per-feature"
    )
    lines.append(
        "page and re-run the renderer (a CI gate fails the PR if the index drifts)."
    )
    lines.append("")
    lines.append(
        "Sections mirror the original `context/feature-inventory.md` numbering"
    )
    lines.append(
        "so existing PLAN.md citations keep working. New features land in the most"
    )
    lines.append(
        "specific section; ambiguous cases go to `10-repos-scope` or `12-ci-gates`."
    )
    lines.append("")

    lines.append(f"Total first-class capabilities: **{len(features)}**.")
    lines.append("")

    for section in sorted(grouped.keys(), key=section_sort_key):
        feats = sorted(grouped[section], key=lambda f: str(f.get("name", "")))
        lines.append(f"## {section}")
        lines.append("")
        lines.append("| Feature | State | Source | Smoke | Runbook | Owner |")
        lines.append("|---|---|---|---|---|---|")
        for feat in feats:
            name = feat.get("name", "?")
            state = feat.get("state", "?")
            sources = feat.get("source", [])
            if isinstance(sources, list):
                source_txt = ", ".join(f"`{s}`" for s in sources) or "?"
            else:
                source_txt = f"`{sources}`"
            smoke = feat.get("smoke", "?")
            runbook = feat.get("runbook", "?")
            owner = feat.get("owner", "?")
            page = feat.get("_path", "")
            smoke_clean = str(smoke).replace("|", "\\|")
            lines.append(
                f"| [{name}]({page}) | {state} | {source_txt} | "
                f"`{smoke_clean}` | `{runbook}` | {owner} |"
            )
        lines.append("")

    lines.append("## States")
    lines.append("")
    lines.append("- **working**: shipped, tested, used in the daily loop.")
    lines.append("- **partial**: implemented but missing adopters or has a known caveat.")
    lines.append("- **aspirational**: documented but not yet implemented.")
    lines.append("- **undocumented**: implemented but missing a feature page.")
    lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Render features index")
    parser.add_argument("features_dir", type=pathlib.Path)
    args = parser.parse_args(argv)
    if not args.features_dir.is_dir():
        print(f"render_index: {args.features_dir} not a directory", file=sys.stderr)
        return 1
    features = load_features(args.features_dir)
    sys.stdout.write(render(features))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
