#!/usr/bin/env bash
# install-dev-hooks.sh — install agent-side defensive hooks into a dev
# clone (NOT a worktree). Implements FARM-1.4 plan acceptance:
#
#   "~/Thesis2/repositories/PROTEA/.git/hooks/pre-commit rejects commits
#    whose branch matches ^(task/|feat/T|hookwt/)"
#
# Why this hook exists. The developer's main checkout under
# `~/Thesis2/repositories/<repo>/` is shared with agents only via
# read-only memory (CLAUDE.md hard constraint). Janitor agents have
# repeatedly done `gh pr checkout <num>` from inside the dev clone,
# which:
#   1. switches the dev's working branch to `task/<id>` or `feat/T...`
#      without the dev noticing,
#   2. potentially commits agent work to the wrong git-dir (no FARM-1.1
#      hooks installed in the main checkout).
#
# This installer drops a pre-commit hook into the dev clone that refuses
# any commit on a branch whose name looks like an agent-owned branch.
# The hook is intentionally narrow: it doesn't block dev work on
# `feat/<area>` or any other human-named branch.
#
# Usage:
#   bash install-dev-hooks.sh [dev_clone_path]   # default: $HOME/Thesis2/repositories/PROTEA
#   bash install-dev-hooks.sh --uninstall [dev_clone_path]
#   bash install-dev-hooks.sh --all              # install into every Thesis2/repositories/* clone
#
# Idempotent. Refuses to write into a directory that is a linked
# worktree (those are handled by scripts/lib/install-hooks.sh).
#
# Bypass switch:
#   AGENT_FARM_SKIP_DEV_HOOKS=1  pre-commit no-ops (rollback / dev-override).

set -euo pipefail

UNINSTALL=0
ALL=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall) UNINSTALL=1; shift ;;
    --all)       ALL=1; shift ;;
    -h|--help)
      cat <<'USAGE'
install-dev-hooks.sh — drop pre-commit guard into the dev clone(s)

  install-dev-hooks.sh                                 # PROTEA only
  install-dev-hooks.sh path/to/clone                   # specific clone
  install-dev-hooks.sh --all                           # every Thesis2/repositories/* clone
  install-dev-hooks.sh --uninstall [path]              # remove the hook

The hook rejects commits on agent-owned branches (^task/, ^feat/T,
^hookwt/). Bypass with AGENT_FARM_SKIP_DEV_HOOKS=1 if you really must.
USAGE
      exit 0
      ;;
    *)
      break
      ;;
  esac
done

REPOS_ROOT="${AGENT_FARM_REPOS_ROOT:-$HOME/Thesis2/repositories}"

_install_one() {
  local clone="$1"

  if [[ ! -d "$clone" ]]; then
    echo "install-dev-hooks: clone path does not exist: $clone" >&2
    return 2
  fi

  # Resolve to absolute path.
  clone=$(cd "$clone" && pwd -P)

  if ! git -C "$clone" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "install-dev-hooks: not a git work tree: $clone" >&2
    return 2
  fi

  # Refuse to install into a linked worktree. Those use FARM-1.1 per-worktree
  # hooks (install-hooks.sh) instead.
  local git_dir common_dir
  git_dir=$(git -C "$clone" rev-parse --git-dir)
  common_dir=$(git -C "$clone" rev-parse --git-common-dir)
  [[ "$git_dir" = /* ]]    || git_dir=$(cd "$clone" && cd "$git_dir" && pwd -P)
  [[ "$common_dir" = /* ]] || common_dir=$(cd "$clone" && cd "$common_dir" && pwd -P)
  if [[ "$git_dir" != "$common_dir" ]]; then
    echo "install-dev-hooks: $clone is a linked worktree; use install-hooks.sh instead" >&2
    return 2
  fi

  local hook_dir hook_path
  hook_dir="$common_dir/hooks"
  hook_path="$hook_dir/pre-commit"
  mkdir -p "$hook_dir"

  if [[ "$UNINSTALL" -eq 1 ]]; then
    if [[ -f "$hook_path" ]] && grep -q 'FARM-1.4 dev-clone guard' "$hook_path"; then
      rm -f "$hook_path"
      echo "install-dev-hooks: removed $hook_path" >&2
    else
      echo "install-dev-hooks: no FARM-1.4 hook at $hook_path (no-op)" >&2
    fi
    return 0
  fi

  # If a non-FARM hook is already there, do not silently clobber it.
  if [[ -f "$hook_path" ]] && ! grep -q 'FARM-1.4 dev-clone guard' "$hook_path"; then
    echo "install-dev-hooks: $hook_path exists and is not a FARM hook; refusing to overwrite" >&2
    echo "(move/delete it manually and re-run; bypass with AGENT_FARM_FORCE_DEV_HOOK=1)" >&2
    if [[ "${AGENT_FARM_FORCE_DEV_HOOK:-0}" != "1" ]]; then
      return 2
    fi
  fi

  cat > "$hook_path" <<'HOOK_EOF'
#!/usr/bin/env bash
# FARM-1.4 dev-clone guard — reject commits on agent-owned branches.
#
# This hook is installed into the developer's main checkout (NOT a
# worktree) by scripts/install-dev-hooks.sh. It refuses any commit
# whose current branch name matches the agent-owned patterns:
#
#   task/<id>     — generated by spawn-subagent.sh (FARM worktrees)
#   feat/T...     — convention for agent-created feature branches
#   hookwt/...    — test-only branch namespace
#
# Rationale: memory feedback_janitor_must_use_worktree — janitor agents
# repeatedly did `gh pr checkout` inside the dev clone, then tried to
# commit. The branch name is the cleanest signal that the agent forgot
# to operate inside its ephemeral worktree.
#
# Bypass: AGENT_FARM_SKIP_DEV_HOOKS=1 git commit ...

set -eu

if [ "${AGENT_FARM_SKIP_DEV_HOOKS:-0}" = "1" ]; then
  exit 0
fi

branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo "")
case "$branch" in
  task/*|feat/T*|hookwt/*)
    printf 'dev-clone guard (FARM-1.4): refusing commit on agent branch %s\n' "$branch" >&2
    printf 'this is the developer dev clone; agents must use a worktree under ~/Thesis2/worktrees/<task_id>/\n' >&2
    printf 'if you are the developer and really want this commit: AGENT_FARM_SKIP_DEV_HOOKS=1 git commit ...\n' >&2
    exit 1
    ;;
esac

exit 0
HOOK_EOF

  chmod +x "$hook_path"
  echo "install-dev-hooks: installed $hook_path" >&2
}

if [[ "$ALL" -eq 1 ]]; then
  [[ -d "$REPOS_ROOT" ]] || { echo "install-dev-hooks: no such repos root: $REPOS_ROOT" >&2; exit 2; }
  rc=0
  for d in "$REPOS_ROOT"/*/; do
    [[ -d "$d/.git" ]] || continue
    _install_one "${d%/}" || rc=$?
  done
  exit $rc
fi

target="${1:-$REPOS_ROOT/PROTEA}"
_install_one "$target"
